apiVersion: v1
kind: Service
metadata:
  name: cygnus-postgresql
  labels:
    app: cygnus-postgresql
spec:
  type: ClusterIP
  selector:
    app: cygnus-postgresql
  ports:
  - port: 5055
    targetPort: service
    name: cygnus-postgresql-service
  - port: 5080
    targetPort: api
    name: cygnus-postgresql-api
